<a href="https://colab.research.google.com/github/vohai2003/Pythoncode/blob/main/BT3_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import os
import numpy
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.linear_model import LinearRegression

MinMaxScaler

In [3]:
def minmaxfit(data):
  scaler = MinMaxScaler()
  scaler.fit(data) #fitting data
  data = scaler.transform(data) #scaling data
  X,y = data[:,:-1], data[:,-1]
  model = LinearRegression()
  model.fit(X,y)
  return model.coef_

In [4]:
data = numpy.loadtxt("/content/gdrive/My Drive/Dataset/ex1data1.txt",delimiter=",")
scaler = MinMaxScaler()
scaler.fit(data) #fitting data
data = scaler.transform(data) #scaling data
X,y = data[:,:-1], data[:,-1]
print(data)

[[6.30643743e-02 7.55662990e-01]
 [2.91567935e-02 4.40250189e-01]
 [2.03288290e-01 6.09172609e-01]
 [1.15061044e-01 5.41779579e-01]
 [4.84917997e-02 3.54260708e-01]
 [1.95387777e-01 5.42972376e-01]
 [1.42610954e-01 2.62005315e-01]
 [2.06752406e-01 5.47221715e-01]
 [8.49610796e-02 3.45888764e-01]
 [1.61270603e-03 2.42186248e-01]
 [3.98111329e-02 2.21148291e-01]
 [5.31965929e-01 6.77870261e-01]
 [4.11676690e-02 2.17528897e-01]
 [1.96872398e-01 3.69263858e-01]
 [3.57357025e-02 1.26618383e-01]
 [2.05227031e-02 2.30865859e-01]
 [7.79280512e-02 2.97658763e-01]
 [6.00834881e-03 1.20825490e-01]
 [8.16658031e-02 2.36043343e-01]
 [1.18996745e-01 3.00808493e-01]
 [6.76637886e-02 2.16913861e-01]
 [8.87459901e-01 9.11285723e-01]
 [2.69677051e-02 2.58825766e-01]
 [7.56399881e-02 2.93286417e-01]
 [3.13225936e-02 2.14822739e-01]
 [8.10317825e-01 9.43752167e-01]
 [4.54183429e-01 6.03171349e-01]
 [3.45252997e-01 3.62587922e-01]
 [4.74444140e-01 6.47565762e-01]
 [1.00000000e+00 1.00000000e+00]
 [1.312870

In [5]:
w = minmaxfit(data)
print("Optimal Coef.:\n",w)

Optimal Coef.:
 [0.7638249]


StandardScaler

In [6]:
def standardfit(data):
  scaler = StandardScaler()
  scaler.fit(data) #fitting data
  data = scaler.transform(data) #scaling data
  X,y = data[:,:-1], data[:,-1]
  model = LinearRegression()
  model.fit(X,y)
  return model.coef_

In [7]:
data = numpy.loadtxt("/content/gdrive/My Drive/Dataset/ex1data2.txt",delimiter=",")
print(data)

[[2.10400e+03 3.00000e+00 3.99900e+05]
 [1.60000e+03 3.00000e+00 3.29900e+05]
 [2.40000e+03 3.00000e+00 3.69000e+05]
 [1.41600e+03 2.00000e+00 2.32000e+05]
 [3.00000e+03 4.00000e+00 5.39900e+05]
 [1.98500e+03 4.00000e+00 2.99900e+05]
 [1.53400e+03 3.00000e+00 3.14900e+05]
 [1.42700e+03 3.00000e+00 1.98999e+05]
 [1.38000e+03 3.00000e+00 2.12000e+05]
 [1.49400e+03 3.00000e+00 2.42500e+05]
 [1.94000e+03 4.00000e+00 2.39999e+05]
 [2.00000e+03 3.00000e+00 3.47000e+05]
 [1.89000e+03 3.00000e+00 3.29999e+05]
 [4.47800e+03 5.00000e+00 6.99900e+05]
 [1.26800e+03 3.00000e+00 2.59900e+05]
 [2.30000e+03 4.00000e+00 4.49900e+05]
 [1.32000e+03 2.00000e+00 2.99900e+05]
 [1.23600e+03 3.00000e+00 1.99900e+05]
 [2.60900e+03 4.00000e+00 4.99998e+05]
 [3.03100e+03 4.00000e+00 5.99000e+05]
 [1.76700e+03 3.00000e+00 2.52900e+05]
 [1.88800e+03 2.00000e+00 2.55000e+05]
 [1.60400e+03 3.00000e+00 2.42900e+05]
 [1.96200e+03 4.00000e+00 2.59900e+05]
 [3.89000e+03 3.00000e+00 5.73900e+05]
 [1.10000e+03 3.00000e+00

In [8]:
w = standardfit(data)
print("Optimal Coef.:\n",w)

Optimal Coef.:
 [ 0.88476599 -0.05317882]
