<a href="https://colab.research.google.com/github/vohai2003/Pythoncode/blob/main/BT_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [4]:
import numpy
import random
A = numpy.zeros((7,5))
for i in range(0,7):
  temp = numpy.zeros((1,5))
  for j in range(0,5):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print(A)

[[31. 39.  3.  5. 20.]
 [22.  3. 13. 25. 14.]
 [ 5. 38.  6. 13. 35.]
 [14. 24. 29. 39. 28.]
 [29.  2. 23. 31. 28.]
 [ 1. 30. 40.  0.  3.]
 [26. 14. 21. 30.  7.]]


Bài 2 $\vec{d}$

In [5]:
A = numpy.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3

In [6]:
A = numpy.zeros((7,7))
for i in range(0,7):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print(A)

[[ 2. 30. 24. 30. 37.  3. 25.]
 [36. 29. 18. 12. 16.  1. 18.]
 [40. 25. 24. 36.  0. 27. 37.]
 [12. 15.  6. 17. 31.  9. 37.]
 [12. 34. 29. 39. 37.  6.  1.]
 [23. 24. 14.  8. 22. 23. 32.]
 [20. 22. 25. 35. 21.  6.  4.]]


Bài 4

In [7]:
A = numpy.zeros((6,6))
for i in range(0,6):
  temp = numpy.zeros((1,6))
  for j in range(0,6):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
for i in range(0,6):
  A[i][i] = 0
print(A)

[[ 0. 15. 35. 40. 36. 26.]
 [12.  0. 12.  1. 38.  8.]
 [33. 10.  0.  9.  8. 29.]
 [ 7. 10. 39.  0. 28. 38.]
 [23.  7. 23.  0.  0.  7.]
 [24. 26. 28. 12. 32.  0.]]


Bài 5

In [11]:
A = numpy.zeros((8,8))
for i in range(0,8):
  temp = numpy.zeros((1,8))
  for j in range(0,8):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
A = numpy.triu(A)
print(A)

[[19. 15. 16. 17. 23.  5. 33. 27.]
 [ 0. 17. 18. 36. 20. 34.  3. 16.]
 [ 0.  0. 39. 28.  8.  6. 40. 12.]
 [ 0.  0.  0. 34. 32. 38. 40. 16.]
 [ 0.  0.  0.  0. 17. 13. 10. 10.]
 [ 0.  0.  0.  0.  0.  8. 28. 26.]
 [ 0.  0.  0.  0.  0.  0. 20. 12.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.]]


Bài 6

In [12]:
A = numpy.zeros((8,8))
for i in range(0,8):
  temp = numpy.zeros((1,8))
  for j in range(0,8):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
A = numpy.tril(A)
print(A)

[[21.  0.  0.  0.  0.  0.  0.  0.]
 [11. 38.  0.  0.  0.  0.  0.  0.]
 [23. 29. 26.  0.  0.  0.  0.  0.]
 [21. 12. 23. 16.  0.  0.  0.  0.]
 [ 7. 15. 17. 18. 19.  0.  0.  0.]
 [22. 29.  8. 32. 38. 27.  0.  0.]
 [37.  8. 22.  6. 39.  6. 29.  0.]
 [36. 34. 28. 30.  8. 24. 35. 40.]]


Bài 7

In [10]:
A = numpy.identity(9)
print(A)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8: Phép cộng ma trận: $A+B$

In [19]:
A = numpy.zeros((6,7))
for i in range(0,6):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print("A =",A )
B = numpy.zeros((6,7))
for i in range(0,6):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  B[i] = temp
print("B =",B )
print("A+B=",A+B)

A = [[40. 32.  9. 35. 30. 39. 19.]
 [ 3. 13. 21. 32. 21.  1. 40.]
 [26. 28. 14.  4.  1. 12. 20.]
 [11. 26. 28. 34.  5. 38.  9.]
 [27. 36. 33. 18.  3. 30.  4.]
 [18. 29. 36.  2. 38.  5. 17.]]
B = [[10. 26. 10. 13. 29. 32. 18.]
 [ 6. 28. 22.  7.  1.  9. 39.]
 [ 8. 10. 14. 33. 33. 38. 28.]
 [37.  9. 30. 22.  7. 10. 16.]
 [ 1.  8. 18. 15. 17. 20. 26.]
 [13.  6. 27. 40. 26. 17.  5.]]
A+B= [[50. 58. 19. 48. 59. 71. 37.]
 [ 9. 41. 43. 39. 22. 10. 79.]
 [34. 38. 28. 37. 34. 50. 48.]
 [48. 35. 58. 56. 12. 48. 25.]
 [28. 44. 51. 33. 20. 50. 30.]
 [31. 35. 63. 42. 64. 22. 22.]]


Phép nhân vô hướng: $n\cdot A$

In [20]:
A = numpy.zeros((5,8))
for i in range(0,5):
  temp = numpy.zeros((1,8))
  for j in range(0,8):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print("A =",A)
n = int(input("Nhap n: "))
print("n*A=",n*A)

A = [[39. 36. 19. 40. 22. 33. 38.  9.]
 [12. 18. 11. 40. 30. 28. 10.  2.]
 [13. 40. 33. 19.  4. 40. 17. 36.]
 [29. 29. 16. 38. 22.  8. 31. 13.]
 [30. 19.  7. 14. 36. 29. 27.  6.]]
Nhap n: 3
n*A= [[117. 108.  57. 120.  66.  99. 114.  27.]
 [ 36.  54.  33. 120.  90.  84.  30.   6.]
 [ 39. 120.  99.  57.  12. 120.  51. 108.]
 [ 87.  87.  48. 114.  66.  24.  93.  39.]
 [ 90.  57.  21.  42. 108.  87.  81.  18.]]


Phép chuyển vị ma trận

In [23]:
A = numpy.zeros((3,7))
for i in range(0,3):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print("A =",A)
print("A chuyen vi:",numpy.transpose(A))

A = [[16. 17. 40. 40. 26. 30. 23.]
 [ 5. 16. 38. 32. 35. 22. 14.]
 [37. 30. 33.  4.  8. 34. 38.]]
A chuyen vi: [[16.  5. 37.]
 [17. 16. 30.]
 [40. 38. 33.]
 [40. 32.  4.]
 [26. 35.  8.]
 [30. 22. 34.]
 [23. 14. 38.]]


Phép nhân hai ma trận: $A_{5*7}\cdot B_{7*3}$

In [25]:
A = numpy.zeros((5,7))
for i in range(0,5):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print("A =",A )
B = numpy.zeros((7,3))
for i in range(0,7):
  temp = numpy.zeros((1,3))
  for j in range(0,3):
    temp[0][j] = random.randint(1,40)
  B[i] = temp
print("B =",B )
print("A*B=",numpy.dot(A,B))

A = [[ 7. 24. 15. 21. 24.  4. 38.]
 [ 5. 31.  7. 36. 12. 13. 17.]
 [11. 25. 36. 23. 30. 37. 27.]
 [27. 22. 16. 37. 11. 19.  6.]
 [14. 28.  7. 15. 12.  2. 40.]]
B = [[34.  1.  8.]
 [34. 22. 15.]
 [22.  1. 19.]
 [38. 37. 33.]
 [ 8. 18. 33.]
 [34. 37. 14.]
 [30.  5. 38.]]
A*B= [[3650. 2097. 3686.]
 [3794. 2808. 3050.]
 [5198. 3492. 4440.]
 [4338. 2827. 2928.]
 [3516. 1682. 3104.]]


Ma trận nghịch đảo: $A^{-1}$

In [28]:
A = numpy.zeros((7,7))
for i in range(0,7):
  temp = numpy.zeros((1,7))
  for j in range(0,7):
    temp[0][j] = random.randint(1,40)
  A[i] = temp
print("A =",A )
print("A^-1=",numpy.linalg.inv(A))

A = [[33. 25.  3.  1. 24. 16. 35.]
 [ 4.  6. 39. 26. 15. 19. 31.]
 [ 8. 31. 27.  3. 16. 36.  7.]
 [ 4.  5. 40. 17. 14.  9. 22.]
 [ 8. 32.  4.  8. 18. 34. 37.]
 [ 2. 37. 26.  2.  1. 19. 16.]
 [25.  2. 11. 31. 21.  3. 18.]]
A^-1= [[ 0.04863474  0.08788546  0.01270267 -0.09806015 -0.06627941  0.01316852
  -0.00647884]
 [-0.02272066 -0.07071267 -0.00941117  0.04861071  0.02909357  0.02865181
   0.02493707]
 [ 0.00970021  0.0142151   0.00676206  0.00762674 -0.02388272  0.0057094
  -0.01127712]
 [-0.02745189  0.00636584 -0.00640063 -0.02057636  0.009962    0.01508899
   0.03616342]
 [-0.03671693 -0.15236138  0.00928831  0.15970439  0.07282125 -0.04415528
   0.02454883]
 [ 0.0169103   0.0923425   0.02933783 -0.09326267 -0.02672651 -0.0140799
  -0.0218836 ]
 [ 0.01634465  0.02850795 -0.02543197 -0.00920827  0.00575661  0.00291234
  -0.01859976]]


Bài 9: Ma trận hàng: $A_{m*1}$

In [29]:
A = numpy.zeros((1,8))
for j in range(0,8):
  A[0][j] = random.randint(1,40)
print(A)

[[ 2. 39. 29. 32. 10. 14.  1.  4.]]


Ma trận cột: $A_{1*n}$

In [32]:
A = numpy.zeros((8,1))
for j in range(0,8):
  A[j][0] = random.randint(1,40)
print(A)

[[15.]
 [37.]
 [23.]
 [37.]
 [14.]
 [ 1.]
 [ 1.]
 [40.]]


Bài 10

In [38]:
m = int(input("So pt cua he phuong trinh:"))
n = int(input("So an cua he phuong trinh:"))
A = numpy.zeros((m,n))
B = numpy.zeros((m,1))
for i in range(0,m):
  for j in range(0,n):
    A[i][j] = int(input("a("+str(i+1)+","+str(j+1)+")= "))
  B[i][0] = int(input("b("+str(i+1)+")= "))
if numpy.isfinite(numpy.linalg.cond(A)):
    x = numpy.dot(numpy.linalg.inv(A),B)
else:
    print("No solution")
print(x)

So pt cua he phuong trinh:2
So an cua he phuong trinh:2
a(1,1)= 54
a(1,2)= 6
b(1,2)= 3
a(2,1)= 5
a(2,2)= 4
b(2,2)= 3
[[-0.03225806]
 [ 0.79032258]]
