<a href="https://colab.research.google.com/github/vohai2003/Pythoncode/blob/main/BT_Vec_Matr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
x = numpy.array([1,2,3,4,5,6])
y = numpy.array([5,6,7,8,9,10])
z = x + y
print(z)
print(z.shape)
print(z.ndim)

[ 6  8 10 12 14 16]
(6,)
1


In [3]:
a = 15
z = a*x
print(z)
print(z.shape)
print(z.ndim)

[15 30 45 60 75 90]
(6,)
1


In [4]:
z = numpy.dot(x,y)
print(z)
print(z.shape)
print(z.ndim)

175
()
0


In [6]:
z = numpy.cross(x[:2],y[:2])
print(z)
print(z.shape)
print(z.ndim)

-4
()
0


In [7]:
z = x*y
print(z)
print(z.shape)
print(z.ndim)

[ 5 12 21 32 45 60]
(6,)
1


In [8]:
x= x.reshape((2,3))
a = 15
z = a*x
print(z)
print(z.shape)
print(z.ndim)

[[15 30 45]
 [60 75 90]]
(2, 3)
2


In [9]:
z = x.T
print(z)
print(z.shape)
print(z.ndim)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
2


In [10]:
y = y.reshape((3,2))
z = x@y
print(z)
print(z.shape)
print(z.ndim)

[[ 46  52]
 [109 124]]
(2, 2)
2


In [11]:
y = y.reshape((2,3))
z = x*y
print(z)
print(z.shape)
print(z.ndim)

[[ 5 12 21]
 [32 45 60]]
(2, 3)
2


In [12]:
z = x.reshape((6,1))
print(z)
print(z.shape)
print(z.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
2


In [13]:
z = x[0,:].reshape((3,1))
print(z)
print(z.shape)
print(z.ndim)

[[1]
 [2]
 [3]]
(3, 1)
2


In [14]:
z = x[:,0].reshape((2,1))
print(z)
print(z.shape)
print(z.ndim)

[[1]
 [4]]
(2, 1)
2
