<a href="https://colab.research.google.com/github/vohai2003/Pythoncode/blob/main/B%C3%A0i_t%E1%BA%ADp_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: sử dụng numpy.arange()

In [5]:
import numpy
A = numpy.arange(1,8)
print(A)
print("So chieu cua vector: ",A.shape[0])
A = numpy.transpose(A)
print("So chieu cua vector chuyen vi: ",A.shape[0])

So chieu cua vector:  7
So chieu cua vector chuyen vi:  7


Sử dụng linspace

In [6]:
A = numpy.linspace(1,5,7)
print(A)
print("So chieu cua vector: ",A.shape[0])
A = numpy.transpose(A)
print("So chieu cua vector chuyen vi: ",A.shape[0])

So chieu cua vector:  7
So chieu cua vector chuyen vi:  7


Sử dụng logspace

In [7]:
A = numpy.logspace(1,5,7)
print(A)
print("So chieu cua vector: ",A.shape[0])
A = numpy.transpose(A)
print("So chieu cua vector chuyen vi: ",A.shape[0])

[1.00000000e+01 4.64158883e+01 2.15443469e+02 1.00000000e+03
 4.64158883e+03 2.15443469e+04 1.00000000e+05]
So chieu cua vector:  7
So chieu cua vector chuyen vi:  7


Sử dụng random.rand

In [9]:
A = numpy.random.rand((7))
print(A)
print("So chieu cua vector: ",A.shape[0])
A = numpy.transpose(A)
print("So chieu cua vector chuyen vi: ",A.shape[0])

[0.77058851 0.71206668 0.50869325 0.7983255  0.40229941 0.31915955
 0.86247566]
So chieu cua vector:  7
So chieu cua vector chuyen vi:  7


Bài 2: Sử dụng arange

In [12]:
A = numpy.arange(10*7)
A.shape = (10,7)
print(A)
print("Kich thuoc cua ma tran: ",A.shape[0],"x",A.shape[1])
A = numpy.transpose(A)
print("Kich thuoc cua ma tran chuyen vi: ",A.shape[0],"x",A.shape[1])
print("So chieu cua ma tran:",A.ndim)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
Kich thuoc cua ma tran:  10 x 7
Kich thuoc cua ma tran chuyen vi:  7 x 10
So chieu cua ma tran: 2


Sử dụng linspace

In [13]:
A = numpy.linspace(1,5,10*7)
A.shape = (10,7)
print(A)
print("Kich thuoc cua ma tran: ",A.shape[0],"x",A.shape[1])
A = numpy.transpose(A)
print("Kich thuoc cua ma tran chuyen vi: ",A.shape[0],"x",A.shape[1])
print("So chieu cua ma tran:",A.ndim)

[[1.         1.05797101 1.11594203 1.17391304 1.23188406 1.28985507
  1.34782609]
 [1.4057971  1.46376812 1.52173913 1.57971014 1.63768116 1.69565217
  1.75362319]
 [1.8115942  1.86956522 1.92753623 1.98550725 2.04347826 2.10144928
  2.15942029]
 [2.2173913  2.27536232 2.33333333 2.39130435 2.44927536 2.50724638
  2.56521739]
 [2.62318841 2.68115942 2.73913043 2.79710145 2.85507246 2.91304348
  2.97101449]
 [3.02898551 3.08695652 3.14492754 3.20289855 3.26086957 3.31884058
  3.37681159]
 [3.43478261 3.49275362 3.55072464 3.60869565 3.66666667 3.72463768
  3.7826087 ]
 [3.84057971 3.89855072 3.95652174 4.01449275 4.07246377 4.13043478
  4.1884058 ]
 [4.24637681 4.30434783 4.36231884 4.42028986 4.47826087 4.53623188
  4.5942029 ]
 [4.65217391 4.71014493 4.76811594 4.82608696 4.88405797 4.94202899
  5.        ]]
Kich thuoc cua ma tran:  10 x 7
Kich thuoc cua ma tran chuyen vi:  7 x 10
So chieu cua ma tran: 2


Sử dụng logspace

In [14]:
A = numpy.logspace(1,5,10*7)
A.shape = (10,7)
print(A)
print("Kich thuoc cua ma tran: ",A.shape[0],"x",A.shape[1])
A = numpy.transpose(A)
print("Kich thuoc cua ma tran chuyen vi: ",A.shape[0],"x",A.shape[1])
print("So chieu cua ma tran:",A.ndim)

[[1.00000000e+01 1.14280206e+01 1.30599655e+01 1.49249555e+01
  1.70562698e+01 1.94919403e+01 2.22754295e+01]
 [2.54564067e+01 2.90916341e+01 3.32459793e+01 3.79935737e+01
  4.34191342e+01 4.96194760e+01 5.67052394e+01]
 [6.48028644e+01 7.40568469e+01 8.46323172e+01 9.67179864e+01
  1.10529514e+02 1.26313356e+02 1.44351164e+02]
 [1.64964807e+02 1.88522122e+02 2.15443469e+02 2.46209240e+02
  2.81368427e+02 3.21548418e+02 3.67466194e+02]
 [4.19941123e+02 4.79909581e+02 5.48441658e+02 6.26760256e+02
  7.16262912e+02 8.18546731e+02 9.35436890e+02]
 [1.06901920e+03 1.22167735e+03 1.39613539e+03 1.59550640e+03
  1.82334800e+03 2.08372585e+03 2.38128619e+03]
 [2.72133877e+03 3.10995155e+03 3.55405904e+03 4.06158599e+03
  4.64158883e+03 5.30441728e+03 6.06189899e+03]
 [6.92755066e+03 7.91681916e+03 9.04735724e+03 1.03393385e+04
  1.18158173e+04 1.35031404e+04 1.54314166e+04]
 [1.76350547e+04 2.01533769e+04 2.30313206e+04 2.63202406e+04
  3.00788252e+04 3.43741434e+04 3.92828419e+04]
 [4.489251

Sử dụng random.rand

In [15]:
A = numpy.random.rand(10,7)
print(A)
print("Kich thuoc cua ma tran: ",A.shape[0],"x",A.shape[1])
A = numpy.transpose(A)
print("Kich thuoc cua ma tran chuyen vi: ",A.shape[0],"x",A.shape[1])
print("So chieu cua ma tran:",A.ndim)

[[0.57381073 0.08247363 0.92836925 0.12175853 0.83070786 0.13948499
  0.96706496]
 [0.69079041 0.4599384  0.36551238 0.48377541 0.81478656 0.52528605
  0.17062205]
 [0.93583048 0.82942514 0.70964247 0.14203697 0.2958464  0.86911043
  0.30858689]
 [0.92338914 0.48758718 0.08153095 0.03144176 0.98186737 0.19772461
  0.87712847]
 [0.15490189 0.58795508 0.77406344 0.28949431 0.64882096 0.20831855
  0.35589009]
 [0.03210234 0.93564386 0.2719227  0.39498556 0.76987628 0.97011935
  0.64699629]
 [0.72504219 0.71330943 0.49029427 0.85299885 0.35628641 0.60091319
  0.83615788]
 [0.1991762  0.43217987 0.57256905 0.13982457 0.99084388 0.79834948
  0.68864416]
 [0.85484487 0.05821126 0.26990165 0.8343398  0.01504428 0.52423057
  0.44325934]
 [0.22967713 0.50827148 0.76239517 0.53128219 0.379989   0.35109252
  0.27190786]]
Kich thuoc cua ma tran:  10 x 7
Kich thuoc cua ma tran chuyen vi:  7 x 10
So chieu cua ma tran: 2


Bài 3: Chuyển ma trận A thành vector

In [16]:
A = A.flatten()
print(A)

[0.57381073 0.69079041 0.93583048 0.92338914 0.15490189 0.03210234
 0.72504219 0.1991762  0.85484487 0.22967713 0.08247363 0.4599384
 0.82942514 0.48758718 0.58795508 0.93564386 0.71330943 0.43217987
 0.05821126 0.50827148 0.92836925 0.36551238 0.70964247 0.08153095
 0.77406344 0.2719227  0.49029427 0.57256905 0.26990165 0.76239517
 0.12175853 0.48377541 0.14203697 0.03144176 0.28949431 0.39498556
 0.85299885 0.13982457 0.8343398  0.53128219 0.83070786 0.81478656
 0.2958464  0.98186737 0.64882096 0.76987628 0.35628641 0.99084388
 0.01504428 0.379989   0.13948499 0.52528605 0.86911043 0.19772461
 0.20831855 0.97011935 0.60091319 0.79834948 0.52423057 0.35109252
 0.96706496 0.17062205 0.30858689 0.87712847 0.35589009 0.64699629
 0.83615788 0.68864416 0.44325934 0.27190786]


Chuyển vector A thành ma trận

In [18]:
A.shape = (10,7)
print(A)

[[0.57381073 0.69079041 0.93583048 0.92338914 0.15490189 0.03210234
  0.72504219]
 [0.1991762  0.85484487 0.22967713 0.08247363 0.4599384  0.82942514
  0.48758718]
 [0.58795508 0.93564386 0.71330943 0.43217987 0.05821126 0.50827148
  0.92836925]
 [0.36551238 0.70964247 0.08153095 0.77406344 0.2719227  0.49029427
  0.57256905]
 [0.26990165 0.76239517 0.12175853 0.48377541 0.14203697 0.03144176
  0.28949431]
 [0.39498556 0.85299885 0.13982457 0.8343398  0.53128219 0.83070786
  0.81478656]
 [0.2958464  0.98186737 0.64882096 0.76987628 0.35628641 0.99084388
  0.01504428]
 [0.379989   0.13948499 0.52528605 0.86911043 0.19772461 0.20831855
  0.97011935]
 [0.60091319 0.79834948 0.52423057 0.35109252 0.96706496 0.17062205
  0.30858689]
 [0.87712847 0.35589009 0.64699629 0.83615788 0.68864416 0.44325934
  0.27190786]]


Bài 4

In [19]:
A = numpy.logspace(1,5,10*15)
A.shape = (10,15)
print(A)
print("Dong thu 3 cua ma tran:\n",A[2])
print("Cot thu 5 cua ma tran:\n",A[:,4])

[[1.00000000e+01 1.06376485e+01 1.13159567e+01 1.20375170e+01
  1.28050875e+01 1.36216020e+01 1.44901815e+01 1.54141458e+01
  1.63970266e+01 1.74425806e+01 1.85548042e+01 1.97379486e+01
  2.09965360e+01 2.23353771e+01 2.37595891e+01]
 [2.52746159e+01 2.68862481e+01 2.86006458e+01 3.04243618e+01
  3.23643668e+01 3.44280759e+01 3.66233771e+01 3.89586614e+01
  4.14428548e+01 4.40854524e+01 4.68965549e+01 4.98869069e+01
  5.30679382e+01 5.64518076e+01 6.00514488e+01]
 [6.38806207e+01 6.79539592e+01 7.22870335e+01 7.68964057e+01
  8.17996938e+01 8.70156393e+01 9.25641789e+01 9.84665203e+01
  1.04745224e+02 1.11424288e+02 1.18529241e+02 1.26087241e+02
  1.34127175e+02 1.42679775e+02 1.51777730e+02]
 [1.61455815e+02 1.71751022e+02 1.82702700e+02 1.94352711e+02
  2.06745584e+02 2.19928686e+02 2.33952406e+02 2.48870348e+02
  2.64739529e+02 2.81620607e+02 2.99578103e+02 3.18680658e+02
  3.39001283e+02 3.60617651e+02 3.83612383e+02]
 [4.08073370e+02 4.34094109e+02 4.61774057e+02 4.91219013e+02
  

Bài 5: Phần xây dựng hàm

In [35]:
import math
def arrange(a):
  left = 0
  right = a.shape[0]-1
  k = 0
  i = 0
  while (left<right):
    for i in range(left,right):
      if a[i] > a[i+1]:
        a[i],a[i+1] = a[i+1],a[i]
        k = i
    right = k
    for i in range(right,left,-1):
      if (a[i]<a[i-1]):
        a[i],a[i-1] = a[i-1],a[i]
        k = i
    left = k
  return(a)
def avg(a):
  shape = a.shape
  length = 1
  for dim in shape:
    length *= dim
  return numpy.sum(a)/length
def median(a):
  a = a.flatten()
  a = arrange(a)
  length = a.shape[0]
  if length%2==1:
    me = a[length//2]
  else:
    me = (a[length//2-1]+a[length//2])/2
  return me
def mode(a):
  a = a.flatten()
  a = arrange(a)
  length = a.shape[0]
  valuelist = []
  occurrence = []
  for i in range(0,length):
    if a[i] not in valuelist:
      valuelist.append(a[i])
      occurrence.append(1)
    else:
      index = valuelist.index(a[i])
      occurrence[index] +=1
  if max(occurrence) == 1:
    return False
  else:
    mode = []
    maxoccur = max(occurrence)
    for i in range(0,len(valuelist)):
      if occurrence[i] == maxoccur:
        mode.append(valuelist[i])
    return(mode)
def variance(a):
  a = a.flatten()
  a = arrange(a)
  length = a.shape[0]
  mu = avg(a)
  vari = 0
  for i in a:
    vari += ((i-mu)**2)/length
  return vari
def stddevi(a):
  return math.sqrt(variance(a))

Phần chương trình chính

In [44]:
A = numpy.arange(0,15*10)
A.shape = (15,10)
print(A)
print("Trung bình của từng hàng:",numpy.apply_along_axis(avg,1,A))
print("Trung vị của từng hàng:",numpy.apply_along_axis(median,1,A))
print("Yếu vị của từng hàng",numpy.apply_along_axis(mode,1,A))
print("Phương sai của từng hàng",numpy.apply_along_axis(variance,1,A))
print("Độ lệch chuẩn của từng hàng",numpy.apply_along_axis(stddevi,1,A))
print("Trung bình của từng cột:",numpy.apply_along_axis(avg,0,A))
print("Trung vị của từng cột:",numpy.apply_along_axis(median,0,A))
print("Yếu vị của từng cột",numpy.apply_along_axis(mode,0,A))
print("Phương sai của từng cột",numpy.apply_along_axis(variance,0,A))
print("Độ lệch chuẩn của từng cột",numpy.apply_along_axis(stddevi,0,A))

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
Trung bình của từng hàng: [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]
Trung vị của từng hàng: [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]
Yếu vị của từng hàng [False False False False False False False False False False False False
 False False False]
Phươ